# Generated by Django 3.0.5 on 2020-04-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200426_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
    ]
