# Generated by Django 3.0.5 on 2020-04-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_member_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
    ]
